image: alpine:latest

stages:
- test
- deploy

before_script: |
  apk update
  apk add python3 nodejs npm

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

pages:
  stage: deploy
  script: |
    npm install . --save-dev
    sh ./Build.sh
    mv ./Dist ./public
    cp ./public/Friendiiverse.html ./public/index.html
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

