image: alpine:latest

stages:
- test
- deploy

before_script: |
  apk update
  apk add python3

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

pages:
  stage: deploy
  script: |
    python3 ./Build.py
    mv ./Dist ./public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

